### PR TITLE
Stop making all items selectable in NavigationView

### PR DESCRIPTION
**Pull request by AnimbusDev**
For options like settings it breaks a few things

### CODE REVIEW

**Comment by julian200601** [comment]
What do you mean exactly?

**Comment by AnimbusDev** [comment]
@julian200601 For example, if your drawer has two sections (like Phonograph) one is selectable, and one isn't. The selectable ones work like standard, but when it goes to the unselectable (settings, report a bug, help and feedback, etc) is selects it. That is the issue.

**Comment by julian200601** [comment]
Not happening to me using NavigationView and two menu groups

**Comment by AnimbusDev** [comment]
@julian200601 Make one not selectable and you will see the issue

**Comment by AnimbusDev** [comment]
@julian200601 Like so

```
<?xml version="1.0" encoding="utf-8"?>
<menu xmlns:android="http://schemas.android.com/apk/res/android">
    <group
        android:id="@+id/navdrawer_main_category"
        android:checkableBehavior="single">
        <item
            android:id="@+id/navdrawer_songs"
            android:icon="@drawable/ic_audiotrack_24dp"
            android:title="@string/page_songs" />

        <item
            android:id="@+id/navdrawer_album_icon"
            android:icon="@drawable/ic_album_24dp"
            android:title="@string/page_albums" />

        <item
            android:id="@+id/navdrawer_artists"
            android:icon="@drawable/ic_artist_24dp"
            android:title="@string/page_artists" />

        <item
            android:id="@+id/navdrawer_playlists"
            android:icon="@drawable/ic_queue_music_black_48dp"
            android:title="@string/page_playlists" />
    </group>

    <group
        android:id="@+id/navdrawer_other_category" >
        <item
            android:id="@+id/navdrawer_settings"
            android:icon="@drawable/ic_settings_24dp"
            android:title="@string/action_settings"/>
        <item
            android:id="@+id/navdrawer_report_bug"
            android:icon="@drawable/ic_bug_report_24dp"
            android:title="@string/action_bug_report"/>
    </group>

</menu>
```

**Comment by julian200601** [comment]
@AnimbusDev  Figured out why I didn't have the issue, I do not use 2 groups. My second section is 
<item android:title="...">
<menu>

<item/>
<item/>
<item/>

</menu>
</item>

because I wanted to give it a title.

**Comment by julian200601** [comment]
Looks like this:

screenshot_20160101-203655 1

**Comment by julian200601** [comment]
and the menu is:

<menu xmlns:android="http://schemas.android.com/apk/res/android">

    <group android:checkableBehavior="single">
        <item
            android:id="@+id/ShuffleNav"
            android:icon="@drawable/ic_shuffle_24dp"
            android:title="@string/Shuffle" />
        <item
            android:id="@+id/LibraryNav"
            android:icon="@drawable/ic_my_library_music_24dp"
            android:title="@string/Library" />
        <item
            android:id="@+id/PlaylistsNav"
            android:icon="@drawable/ic_queue_music_24dp"
            android:title="@string/Playlists" />

    </group>

    <item android:title="@string/Other">
        <menu>
            <item
                android:id="@+id/info"
                android:icon="@drawable/ic_info_outline_black_24dp"
                android:title="@string/info" />
            <item
                android:id="@+id/support"
                android:icon="@drawable/ic_audiotrack_black_24dp"
                android:title="@string/support" />
            <item
                android:id="@+id/SettingsNav"
                android:icon="@drawable/ic_settings_24dp"
                android:title="@string/Settings" />

        </menu>
    </item>

</menu>

**Pull request merged**
