### PR TITLE
FloatingActionButton support

### PR DESCRIPTION
**Pull request by julian200601**
-FloatingActionButtonProcessor
-ATEFloatingActionButtonCustomizer for FAB background
-Drawale tint depends on background color (isColorLight...)

### CODE REVIEW

**Comment by afollestad** [comment]
FAB support is actually implemented using selector tags, as seen in the sample project. 

I'd like to avoid having too many configuration options when there's a tag system that works on most views that aren't system UI.

**Comment by afollestad** [comment]
It also does color detection for the text/cons, for anything that inherits a Button.

**Comment by julian200601** [comment]
@afollestad It doesnt for me..
That was the cause for me to add support.

Screenshots:

Current version:
screenshot_20160102-043230 1



Version edited by me:
screenshot_20160102-043407 1

**Comment by julian200601** [comment]
@afollestad  => FloatingActionButton inherits / extends ImageView

**Comment by afollestad** [comment]
@julian200601 `FloatingActionButton` gets themed from the `TintHelper` class when you use a selector tag on it, here's the line where it gets themed (including the ripple): https://github.com/afollestad/app-theme-engine/blob/90ef47177c0215137223c41b8d2d9d086dfd1201/library/src/main/java/com/afollestad/appthemeengine/util/TintHelper.java#L66

Although it looks like I did actually forget to theme the icon in it, thought I did. I'll fix that in a second.

**Comment by julian200601** [comment]
@afollestad  😀😀

**Pull request closed without merging**
