### PR TITLE
Fixing missing Googgle Play image

### PR DESCRIPTION
**Pull request by piotrek1543**

### CODE REVIEW

**Comment by afollestad** [comment]
I'll fix the missing Google Play image myself, I'm not gonna use a spam link

**Comment by piotrek1543** [comment]
Spam link? I found nice big image and make it small especially for this project's README... Spam... Oh, God

**Comment by piotrek1543** [comment]
Actual image seems a way to big, but it's only my personal opinion. Cheers

**Comment by afollestad** [comment]
Yeah, that's just a placeholder, I'll fix it further once I'm back at a
computer 😉

On Sat, Jan 23, 2016, 4:09 PM Piotr Ekert <notifications@github.com> wrote:

> Actual image seems a way to big, but it's only my personal opinion. Cheers
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/afollestad/app-theme-engine/pull/69#issuecomment-174226139>
> .
>
-- 

Regards,

Aidan Follestad
http://aidanfollestad.com
651-528-1662

**Pull request closed without merging**
